server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://111.231.64.120:3306/user_center
    hikari:
      username: root
      password: Zcq960921!
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center