server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://111.231.64.120:3306/user_center
    hikari:
      username: root
      password: Zcq960921!
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: a809b1e2-3bc6-4054-826d-a93716cb56b9 #不同的namespace之间是隔离的，这里是namespace的uuid
        cluster-name: NJ #指定集群名称
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center