server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://111.231.64.120:3306/user_center
    hikari:
      username: root
      password: Zcq960921!
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver